<?php

  /**
   * @file Core hook implementations and functionality for the Module
   * @author griffinj@lafayette.edu
   *
   */

module_load_include('inc', 'islandora_gis_geoserver', '/includes/islandora_gis_geoserver.openlayers');
module_load_include('inc', 'islandora_gis_geoserver', '/includes/islandora_gis_geoserver.layer');
module_load_include('inc', 'islandora_gis_geoserver', '/theme/theme');

/**
 * Implements hook_ctools_plugin_api().
 *
 * Required for OpenLayers integration.
 */
function islandora_gis_geoserver_ctools_plugin_api($module, $api) {

  if($module == 'openlayers') {

    switch ($api) {

    case 'openlayers_layers':
      return array('version' => 1);
    }
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function islandora_gis_geoserver_ctools_plugin_type() {

  return array('layer_types' => array());
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 *
 */
//function islandora_large_image_islandora_sp_large_image_cmodel_islandora_object_ingested($object) {
function islandora_gis_geoserver_islandora_sp_large_image_cmodel_islandora_object_ingested($object) {

  // Verify that this is a GeoTIFF
  
  // Relate this to a Shapefile
}

/**
 * Retrieve the Session Object for Islandora
 * Session Objects provide an interface for Fedora Generic Search and Apache Solr
 *
 */
function islandora_gis_geoserver_get_session($user = 'admin', $pass = 'secret', $url = 'http://localhost:8080/geoserver') {

  $session = &drupal_static(__FUNCTION__);
  if(!$session) {

    try {

      $session = new IslandoraGeoServer\IslandoraGeoServerSession($user, $pass, $url);
    } catch (Exception $e) {

      drupal_set_message(t('Unable to establish an Islandora GeoServer Session: %error', array('%error' => $e)), 'error');
    }
  } else {

    return NULL;
  }

  return $session;
}

/**
 * Implements hook_islandora_gis_map_load_alter().
 *
 */
function islandora_gis_geoserver_islandora_gis_map_load_alter(&$map, $layer_count) {

  //$map['islandora_layers'] = array_merge($map['islandora_layers'], _islandora_gis_geoserver_openlayers_layers($layer_count));

  $islandora_layers = array_merge($map['islandora_layers'], _islandora_gis_geoserver_openlayers_layers($layer_count));
  $map['islandora_layers'] = $islandora_layers;
  
  //$map['islandora_layers'][] = _islandora_gis_geoserver_openlayers_layers($layer_count);
  
  /*
  // Resolve visibility issues here
  foreach($map['islandora_layers'] as &$islandora_layer) {

    $islandora_layer['layer']->data['visibility']
  }
  */
}
